### PR TITLE
Remove mtime update on TrustlineUpdate event

### PR DESCRIPTION
**Pull request by berndbohmeier**

### CODE REVIEW

**Comment by berndbohmeier** [comment]
I was not sure if we might need it again in the future, but I can remove it if you want.

**Comment by berndbohmeier** [comment]
it would then have to change also the calling code.

**Comment by cducrest** [comment]
There is only one places that calls it. I believe it makes sense to remove it (and it is easy to put back when we need it).

**Comment by berndbohmeier** [comment]
Thanks

**Pull request merged**
